language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.1

sudo: false
script:
  - mix compile --warnings-as-errors
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

notifications:
  recipients:
    - pmargreff@gmail.com