language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.1

sudo: false

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  recipients:
    - pmargreff@gmail.com