language: elixir
elixir:
  - 1.8.2
otp_release:
  - 22.0

matrix:
  include:
  - otp_release: 21.1
    elixir: 1.8.1

cache:
  directories:
    - deps
    - _build/

sudo: false

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  recipients:
    - pmargreff@gmail.com